AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quote-generator

  Serverless application to serve motivational quotes via API and email.

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:

  QuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: quote_api/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: QuotesTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: QuotesTable
      Events:
        QuoteAPI:
          Type: Api
          Properties:
            Path: /quote
            Method: get

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscribe/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: SubscribersTable
      Events:
        SubscribeAPI:
          Type: Api
          Properties:
            Path: /subscribe
            Method: post

  UnsubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: unsubscribe/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: SubscribersTable
      Events:
        UnsubscribeAPI:
          Type: Api
          Properties:
            Path: /unsubscribe
            Method: delete

  AddQuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_quote/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: QuotesTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: QuotesTable
      Events:
        AddQuoteAPI:
          Type: Api
          Properties:
            Path: /add-quote
            Method: post
            Auth:
              ApiKeyRequired: true

  DailyEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: daily_email/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: QuotesTable
          SUBSCRIBERS_TABLE: SubscribersTable
          FROM_EMAIL: godwinjayakumar1@gmail.com
          SLACK_WEBHOOK_PARAM: "/daily-email/slackWebhook"
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: QuotesTable
        - DynamoDBReadPolicy:
            TableName: SubscribersTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:us-east-1:*:parameter/daily-email/slackWebhook
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 2 * * ? *)



  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QuotesTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SubscribersTable
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  QuoteApiEndpoint:
    Description: API Gateway endpoint URL for quote function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quote/"

  SubscribeApiEndpoint:
    Description: API Gateway endpoint URL for subscribe function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscribe/"

  UnsubscribeApiEndpoint:
    Description: API Gateway endpoint URL for unsubscribe function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/unsubscribe/"

  AddQuoteApiEndpoint:
    Description: API Gateway endpoint URL for add-quote function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add-quote/"

  QuoteFunction:
    Description: Quote Lambda Function ARN
    Value: !GetAtt QuoteFunction.Arn

  SubscribeFunction:
    Description: Subscribe Lambda Function ARN
    Value: !GetAtt SubscribeFunction.Arn

  UnsubscribeFunction:
    Description: Unsubscribe Lambda Function ARN
    Value: !GetAtt UnsubscribeFunction.Arn

  AddQuoteFunction:
    Description: AddQuote Lambda Function ARN
    Value: !GetAtt AddQuoteFunction.Arn

  DailyEmailFunction:
    Description: Daily Email Lambda Function ARN
    Value: !GetAtt DailyEmailFunction.Arn
