AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: QuoteVerse API

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'300'"

  QuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: quote_api/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !GetAtt QuotesTable.Arn
      Events:
        QuoteAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /quote
            Method: get

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscribe/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt SubscribersTable.Arn
      Events:
        SubscribeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /subscribe
            Method: post

  UnsubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: unsubscribe/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource: !GetAtt SubscribersTable.Arn
      Events:
        UnsubscribeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /unsubscribe
            Method: delete

  AddQuoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_quote/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt QuotesTable.Arn
      Events:
        AddQuoteAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /add-quote
            Method: post
            Auth:
              ApiKeyRequired: true

  DailyEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: daily_email/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures: [x86_64]
      Environment:
        Variables:
          QUOTES_TABLE: !Ref QuotesTable
          SUBSCRIBERS_TABLE: !Ref SubscribersTable
          FROM_EMAIL: godwinjayakumar1@gmail.com
          SLACK_WEBHOOK_PARAM: "/daily-email/slackWebhook"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !GetAtt QuotesTable.Arn
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !GetAtt SubscribersTable.Arn
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/godwinjayakumar1@gmail.com"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/daily-email/slackWebhook"
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 2 * * ? *)

  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QuotesTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SubscribersTable
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

Outputs:
  ApiEndpoint:
    Description: Base URL for API Gateway
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  QuoteApiEndpoint:
    Description: Endpoint for quote function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/quote"
  SubscribeApiEndpoint:
    Description: Endpoint for subscribe function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subscribe"
  UnsubscribeApiEndpoint:
    Description: Endpoint for unsubscribe function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/unsubscribe"
  AddQuoteApiEndpoint:
    Description: Endpoint for add-quote function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add-quote"
  FrontendBucketURL:
    Description: Public URL for the hosted frontend
    Value: !Sub "http://${FrontendBucket}.s3-website-${AWS::Region}.amazonaws.com"
